server:
  port: 4560
  servlet:
    context-path: /

spring:
  redis:
    database: 11
    host: 127.0.0.1
    password: foobared
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 300
        max-idle: 32
        max-wait: 1000
        min-idle: 5


#logback配置
logging:
  config: classpath:logback-spring.xml
logPath: /logs/